### ISSUE TITLE
"Convert to Stateful Component" doesn't work with function expressions

### ISSUE THREAD

**Issue by zackkrida** [wix/vscode-glean#19] opened 2018-10-18 01:22 UTC
```js
// Doesn't work
const button = props => (
  <button type="submit" className={props.className}>
    {props.children}
  </button>
)

// Does work
function button(props) {
  return (
    <button type="submit" className={props.className}>
      {props.children}
    </button>
  )
}
```

**Comment by borislit** [comment] 2018-10-19 11:42
@zackkrida thanks for feedback. I was able to reproduce. Ill handle this ASAP and keep you posed

**Comment by MitchLillie** [comment] 2018-10-22 14:51
I believe this should be tagged Stateless to Stateful. Also having this issue, seeing the error:

```
Property body of ClassMethod expected node to be of a type ["BlockStatement"] but instead got "JSXElement"
```

**Comment by borislit** [comment] 2018-10-22 19:06
@MitchLillie can you please provide an example of code you are trying to refactor?

**Comment by borislit** [comment] 2018-10-22 21:04
@zackkrida Fixed by https://github.com/wix/vscode-glean/commit/c9361351eb45e55779758d69d163a836bd264caa

**Comment by borislit** [comment] 2018-10-22 21:12
I will release the version with the fix as soon as recent Github issues are resolved.

**Comment by borislit** [comment] 2018-10-23 06:53
@zackkrida Released https://github.com/wix/vscode-glean/releases/tag/v3.3.3 that includes the fix

**Comment by DominicTobias** [comment] 2018-10-25 08:58
Hi I have 4.0.2 but have no option to convert the `const` style of function to a stateful function which is the only reason I installed it!

![no-worky](https://user-images.githubusercontent.com/760314/47488524-78bba180-d83c-11e8-92da-fd718d2618ff.jpg)

**Comment by borislit** [comment] 2018-10-25 09:05
@DominicTobias the issue the resst in props. The extension code that detects possible actions on selected code seems to have an issue with that. Will fix it ASAP. 
For now, if you convert the props object to simple destructuring or remove it all together and just use "props" parameters - it should work. 
![image](https://user-images.githubusercontent.com/1139234/47488954-1a97ba00-d84e-11e8-8f27-4f628dded96a.png)
![image](https://user-images.githubusercontent.com/1139234/47488973-2b483000-d84e-11e8-95da-1d2eb2381941.png)

**Comment by DominicTobias** [comment] 2018-10-25 09:07
Ah ok thanks :)

**Comment by borislit** [comment] 2018-10-25 09:46
@DominicTobias I've added support for the rest operator in props :) Should be available in v4.0.3 :) Check it out!

**Closed by borislit** 2018-10-25 09:46 UTC
Labels: Stateful to Stateless, bug

**Comment by DominicTobias** [comment] 2018-10-25 09:53
That was fast! No extra menu option is coming up for me though (in 4.0.3), here's the snipper I'm highlighting:

```jsx
const Button = ({
  className,
  children,
  isActive,
  size,
  ...otherProps
}) => (
  <button
    className={classNames('Button', `Button--size${size}`, className, {
      'Button--isActive': isActive,
    })}
    type="button"
    {...otherProps}
  >
    {children}
  </button>
);
```

**Comment by borislit** [comment] 2018-10-25 12:41
@DominicTobias works for me on the latest version:
![image](https://user-images.githubusercontent.com/1139234/47500803-7a04c280-d86c-11e8-8bb4-13c17eaf23c8.png)

**Comment by brownieboy** [comment] 2019-08-20 03:23
@borislit's sample Button code above doesn't work for me with Glean 4.15.2 on VSCode 1.35.1, running on Windows 10.

That "Convert Stateless..." popup menu option simply doesn't appear.

**Comment by borislit** [comment] 2019-08-20 06:59
@brownieboy please provide a code sample you are trying to refactor and ill have a look :)

**Comment by brownieboy** [comment] 2019-08-20 11:05
The Button code in this comment above https://github.com/wix/vscode-glean/issues/19#issuecomment-432989189

**Comment by borislit** [comment] 2019-08-21 19:56
@brownieboy I was unable to reproduce the issue. See the attached GIF. Note that the option DOESNT show up if u select the imports too. Tell me if i can be of any help
![Kapture 2019-08-21 at 22 51 36](https://user-images.githubusercontent.com/1139234/63463944-dfaee480-c466-11e9-92a0-42e0a40e3839.gif)

**Comment by brownieboy** [comment] 2019-08-21 21:33
Thanks for investigating, @borislit .

Still not working for me.  I've tried on two different machines: Windows 10 and Mac OS X Mojave.  I still can't see all the menus.  You can see that I am not highlighting the import statement:

![glean-test](https://user-images.githubusercontent.com/1781909/63469998-d3e71080-c4ae-11e9-80b8-23792098ab1c.jpg)

**Comment by borislit** [comment] 2019-09-01 08:51
@brownieboy Sorry for the delay. havent forgotten about this. Just been a bit busy. Ill have all at this ASAP
